pull_request_rules:
  - name: Add to default queue
    conditions:
      - base=main
      - status-success=build
    actions:
      queue:
        name: mine
queue_rules:
  - queue_branch_merge_method: merge-commit
    merge_method: squash
    update_method: rebase
    name: mine
