pull_request_rules:
  - name: Add to default queue
    conditions:
      - base=main
      - status-success=build
    actions:
      queue:
        name: default
queue_rules:
  - queue_branch_merge_method: fast-forward
    merge_method: squash
    update_method: rebase
    name: mine
