pull_request_rules:
  - name: Add to default queue
    conditions:
      - base=main
      - status-success=build
    actions:
      queue:
        name: mine
queue_rules:
  - name: mine
    merge_method: squash
    update_method: rebase
