name: Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      P6_TEST_COLOR_OFF: "1"
      P6_DFZ_SRC_P6M7G8_DIR: ".."
      ROOT_DIR_REL: ".."
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./scripts/env.sh
